//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbidzarFrame.Web.BOAJMIBondsServiceModel {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BondMastBaseModel", Namespace="http://schemas.datacontract.org/2004/07/Manulife.Id.BOAJMI.Domain.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AbidzarFrame.Web.BOAJMIBondsServiceModel.BondMastResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AbidzarFrame.Web.BOAJMIBondsServiceModel.BondMastRequest))]
    public partial class BondMastBaseModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ACQ_DTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ACQ_PRICEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APPROVEDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BANKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BANK_ACCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BANK_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> BOIR_XCLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BOND_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BOND_INFOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CAP_GAIN_TXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COMMENTARYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DEAL_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DEAL_PRICEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ENT_DTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EXECUTEDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> FEEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GROUP_CDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GUARANTEEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HOLD_PRDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IS_DELETEDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> L_UPD_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string L_USER_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> NOMINALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ORDER_TPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PAYM_INSTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PAY_AGENTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> REPURCHASEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SEC_TYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SETTLEMENTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SETTLE_DTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TAX_RTDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> TRAN_DTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TRAN_TYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TRUSTEEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USER_ID_AField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ACQ_DT {
            get {
                return this.ACQ_DTField;
            }
            set {
                if ((this.ACQ_DTField.Equals(value) != true)) {
                    this.ACQ_DTField = value;
                    this.RaisePropertyChanged("ACQ_DT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ACQ_PRICE {
            get {
                return this.ACQ_PRICEField;
            }
            set {
                if ((this.ACQ_PRICEField.Equals(value) != true)) {
                    this.ACQ_PRICEField = value;
                    this.RaisePropertyChanged("ACQ_PRICE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APPROVED {
            get {
                return this.APPROVEDField;
            }
            set {
                if ((object.ReferenceEquals(this.APPROVEDField, value) != true)) {
                    this.APPROVEDField = value;
                    this.RaisePropertyChanged("APPROVED");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BANK {
            get {
                return this.BANKField;
            }
            set {
                if ((this.BANKField.Equals(value) != true)) {
                    this.BANKField = value;
                    this.RaisePropertyChanged("BANK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BANK_ACC {
            get {
                return this.BANK_ACCField;
            }
            set {
                if ((object.ReferenceEquals(this.BANK_ACCField, value) != true)) {
                    this.BANK_ACCField = value;
                    this.RaisePropertyChanged("BANK_ACC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BANK_CODE {
            get {
                return this.BANK_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.BANK_CODEField, value) != true)) {
                    this.BANK_CODEField = value;
                    this.RaisePropertyChanged("BANK_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BES {
            get {
                return this.BESField;
            }
            set {
                if ((this.BESField.Equals(value) != true)) {
                    this.BESField = value;
                    this.RaisePropertyChanged("BES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> BOIR_XCL {
            get {
                return this.BOIR_XCLField;
            }
            set {
                if ((this.BOIR_XCLField.Equals(value) != true)) {
                    this.BOIR_XCLField = value;
                    this.RaisePropertyChanged("BOIR_XCL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BOND_CODE {
            get {
                return this.BOND_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.BOND_CODEField, value) != true)) {
                    this.BOND_CODEField = value;
                    this.RaisePropertyChanged("BOND_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BOND_INFO {
            get {
                return this.BOND_INFOField;
            }
            set {
                if ((object.ReferenceEquals(this.BOND_INFOField, value) != true)) {
                    this.BOND_INFOField = value;
                    this.RaisePropertyChanged("BOND_INFO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CAP_GAIN_TX {
            get {
                return this.CAP_GAIN_TXField;
            }
            set {
                if ((this.CAP_GAIN_TXField.Equals(value) != true)) {
                    this.CAP_GAIN_TXField = value;
                    this.RaisePropertyChanged("CAP_GAIN_TX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COMMENTARY {
            get {
                return this.COMMENTARYField;
            }
            set {
                if ((object.ReferenceEquals(this.COMMENTARYField, value) != true)) {
                    this.COMMENTARYField = value;
                    this.RaisePropertyChanged("COMMENTARY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DEAL_NO {
            get {
                return this.DEAL_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.DEAL_NOField, value) != true)) {
                    this.DEAL_NOField = value;
                    this.RaisePropertyChanged("DEAL_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DEAL_PRICE {
            get {
                return this.DEAL_PRICEField;
            }
            set {
                if ((this.DEAL_PRICEField.Equals(value) != true)) {
                    this.DEAL_PRICEField = value;
                    this.RaisePropertyChanged("DEAL_PRICE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ENT_DT {
            get {
                return this.ENT_DTField;
            }
            set {
                if ((this.ENT_DTField.Equals(value) != true)) {
                    this.ENT_DTField = value;
                    this.RaisePropertyChanged("ENT_DT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EXECUTED {
            get {
                return this.EXECUTEDField;
            }
            set {
                if ((object.ReferenceEquals(this.EXECUTEDField, value) != true)) {
                    this.EXECUTEDField = value;
                    this.RaisePropertyChanged("EXECUTED");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> FEE {
            get {
                return this.FEEField;
            }
            set {
                if ((this.FEEField.Equals(value) != true)) {
                    this.FEEField = value;
                    this.RaisePropertyChanged("FEE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GROUP_CD {
            get {
                return this.GROUP_CDField;
            }
            set {
                if ((object.ReferenceEquals(this.GROUP_CDField, value) != true)) {
                    this.GROUP_CDField = value;
                    this.RaisePropertyChanged("GROUP_CD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GUARANTEE {
            get {
                return this.GUARANTEEField;
            }
            set {
                if ((object.ReferenceEquals(this.GUARANTEEField, value) != true)) {
                    this.GUARANTEEField = value;
                    this.RaisePropertyChanged("GUARANTEE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HOLD_PRD {
            get {
                return this.HOLD_PRDField;
            }
            set {
                if ((this.HOLD_PRDField.Equals(value) != true)) {
                    this.HOLD_PRDField = value;
                    this.RaisePropertyChanged("HOLD_PRD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IS_DELETED {
            get {
                return this.IS_DELETEDField;
            }
            set {
                if ((this.IS_DELETEDField.Equals(value) != true)) {
                    this.IS_DELETEDField = value;
                    this.RaisePropertyChanged("IS_DELETED");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> L_UPD_DATE {
            get {
                return this.L_UPD_DATEField;
            }
            set {
                if ((this.L_UPD_DATEField.Equals(value) != true)) {
                    this.L_UPD_DATEField = value;
                    this.RaisePropertyChanged("L_UPD_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string L_USER_ID {
            get {
                return this.L_USER_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.L_USER_IDField, value) != true)) {
                    this.L_USER_IDField = value;
                    this.RaisePropertyChanged("L_USER_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> NOMINAL {
            get {
                return this.NOMINALField;
            }
            set {
                if ((this.NOMINALField.Equals(value) != true)) {
                    this.NOMINALField = value;
                    this.RaisePropertyChanged("NOMINAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ORDER_TP {
            get {
                return this.ORDER_TPField;
            }
            set {
                if ((this.ORDER_TPField.Equals(value) != true)) {
                    this.ORDER_TPField = value;
                    this.RaisePropertyChanged("ORDER_TP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PAYM_INST {
            get {
                return this.PAYM_INSTField;
            }
            set {
                if ((object.ReferenceEquals(this.PAYM_INSTField, value) != true)) {
                    this.PAYM_INSTField = value;
                    this.RaisePropertyChanged("PAYM_INST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PAY_AGENT {
            get {
                return this.PAY_AGENTField;
            }
            set {
                if ((object.ReferenceEquals(this.PAY_AGENTField, value) != true)) {
                    this.PAY_AGENTField = value;
                    this.RaisePropertyChanged("PAY_AGENT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> REPURCHASE {
            get {
                return this.REPURCHASEField;
            }
            set {
                if ((this.REPURCHASEField.Equals(value) != true)) {
                    this.REPURCHASEField = value;
                    this.RaisePropertyChanged("REPURCHASE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SEC_TYPE {
            get {
                return this.SEC_TYPEField;
            }
            set {
                if ((this.SEC_TYPEField.Equals(value) != true)) {
                    this.SEC_TYPEField = value;
                    this.RaisePropertyChanged("SEC_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SETTLEMENT {
            get {
                return this.SETTLEMENTField;
            }
            set {
                if ((object.ReferenceEquals(this.SETTLEMENTField, value) != true)) {
                    this.SETTLEMENTField = value;
                    this.RaisePropertyChanged("SETTLEMENT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SETTLE_DT {
            get {
                return this.SETTLE_DTField;
            }
            set {
                if ((this.SETTLE_DTField.Equals(value) != true)) {
                    this.SETTLE_DTField = value;
                    this.RaisePropertyChanged("SETTLE_DT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TAX_RTD {
            get {
                return this.TAX_RTDField;
            }
            set {
                if ((this.TAX_RTDField.Equals(value) != true)) {
                    this.TAX_RTDField = value;
                    this.RaisePropertyChanged("TAX_RTD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TRAN_DT {
            get {
                return this.TRAN_DTField;
            }
            set {
                if ((this.TRAN_DTField.Equals(value) != true)) {
                    this.TRAN_DTField = value;
                    this.RaisePropertyChanged("TRAN_DT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TRAN_TYPE {
            get {
                return this.TRAN_TYPEField;
            }
            set {
                if ((this.TRAN_TYPEField.Equals(value) != true)) {
                    this.TRAN_TYPEField = value;
                    this.RaisePropertyChanged("TRAN_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TRUSTEE {
            get {
                return this.TRUSTEEField;
            }
            set {
                if ((object.ReferenceEquals(this.TRUSTEEField, value) != true)) {
                    this.TRUSTEEField = value;
                    this.RaisePropertyChanged("TRUSTEE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USER_ID_A {
            get {
                return this.USER_ID_AField;
            }
            set {
                if ((object.ReferenceEquals(this.USER_ID_AField, value) != true)) {
                    this.USER_ID_AField = value;
                    this.RaisePropertyChanged("USER_ID_A");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BondMastResult", Namespace="http://schemas.datacontract.org/2004/07/Manulife.Id.BOAJMI.Bonds.Interface.Dto")]
    [System.SerializableAttribute()]
    public partial class BondMastResult : AbidzarFrame.Web.BOAJMIBondsServiceModel.BondMastBaseModel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BondMastRequest", Namespace="http://schemas.datacontract.org/2004/07/Manulife.Id.BOAJMI.Bonds.Interface.Dto")]
    [System.SerializableAttribute()]
    public partial class BondMastRequest : AbidzarFrame.Web.BOAJMIBondsServiceModel.BondMastBaseModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthenticationTokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthenticationToken {
            get {
                return this.AuthenticationTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthenticationTokenField, value) != true)) {
                    this.AuthenticationTokenField = value;
                    this.RaisePropertyChanged("AuthenticationToken");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BondMastResponse", Namespace="http://schemas.datacontract.org/2004/07/Manulife.Id.BOAJMI.Bonds.Interface.Dto")]
    [System.SerializableAttribute()]
    public partial class BondMastResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AbidzarFrame.Web.BOAJMIBondsServiceModel.BondMastResult BondMastResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AbidzarFrame.Web.BOAJMIBondsServiceModel.BondMastResult[] BondMastResultListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AbidzarFrame.Web.BOAJMIBondsServiceModel.BusinessErrors ErrorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AbidzarFrame.Web.BOAJMIBondsServiceModel.BondMastResult BondMastResult {
            get {
                return this.BondMastResultField;
            }
            set {
                if ((object.ReferenceEquals(this.BondMastResultField, value) != true)) {
                    this.BondMastResultField = value;
                    this.RaisePropertyChanged("BondMastResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AbidzarFrame.Web.BOAJMIBondsServiceModel.BondMastResult[] BondMastResultList {
            get {
                return this.BondMastResultListField;
            }
            set {
                if ((object.ReferenceEquals(this.BondMastResultListField, value) != true)) {
                    this.BondMastResultListField = value;
                    this.RaisePropertyChanged("BondMastResultList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AbidzarFrame.Web.BOAJMIBondsServiceModel.BusinessErrors Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessErrors", Namespace="http://schemas.datacontract.org/2004/07/Manulife.Core.Model.Business")]
    [System.SerializableAttribute()]
    public partial class BusinessErrors : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AbidzarFrame.Web.BOAJMIBondsServiceModel.BusinessErrorVo[] ErrorListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AbidzarFrame.Web.BOAJMIBondsServiceModel.BusinessErrorVo[] ErrorList {
            get {
                return this.ErrorListField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorListField, value) != true)) {
                    this.ErrorListField = value;
                    this.RaisePropertyChanged("ErrorList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessErrorVo", Namespace="http://schemas.datacontract.org/2004/07/Manulife.Core.Model.Business")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AbidzarFrame.Web.BOAJMIBondsServiceModel.BusinessWarningVo))]
    public partial class BusinessErrorVo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> ErrorMessagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorField {
            get {
                return this.ErrorFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorFieldField, value) != true)) {
                    this.ErrorFieldField = value;
                    this.RaisePropertyChanged("ErrorField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> ErrorMessages {
            get {
                return this.ErrorMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessagesField, value) != true)) {
                    this.ErrorMessagesField = value;
                    this.RaisePropertyChanged("ErrorMessages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessWarningVo", Namespace="http://schemas.datacontract.org/2004/07/Manulife.Core.Model.Business")]
    [System.SerializableAttribute()]
    public partial class BusinessWarningVo : AbidzarFrame.Web.BOAJMIBondsServiceModel.BusinessErrorVo {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BondProdBaseModel", Namespace="http://schemas.datacontract.org/2004/07/Manulife.Id.BOAJMI.Domain.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AbidzarFrame.Web.BOAJMIBondsServiceModel.BondProdResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AbidzarFrame.Web.BOAJMIBondsServiceModel.BondProdRequest))]
    public partial class BondProdBaseModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BOND_PROD_DEFAULTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BOND_PROD_DESCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CATEGORYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CCY_CDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> COUP_DAYSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> COUP_TERMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CUSIPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> INACTIVEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> INT_RTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> INT_TYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISSUERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ISSUE_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IS_DELETEDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KSEI_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LAST_COUPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LAST_COUP_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LIMIT_1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LIMIT_2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> L_UPD_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string L_USER_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> MAT_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NEXT_COUPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NEXT_COUP_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RATINGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SECTORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SEDOLCDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> SYARIAHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TAX_RTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TAX_RT_2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> UNIT_MTDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> YEAR_BSField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BOND_PROD_DEFAULT {
            get {
                return this.BOND_PROD_DEFAULTField;
            }
            set {
                if ((this.BOND_PROD_DEFAULTField.Equals(value) != true)) {
                    this.BOND_PROD_DEFAULTField = value;
                    this.RaisePropertyChanged("BOND_PROD_DEFAULT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BOND_PROD_DESC {
            get {
                return this.BOND_PROD_DESCField;
            }
            set {
                if ((object.ReferenceEquals(this.BOND_PROD_DESCField, value) != true)) {
                    this.BOND_PROD_DESCField = value;
                    this.RaisePropertyChanged("BOND_PROD_DESC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CATEGORY {
            get {
                return this.CATEGORYField;
            }
            set {
                if ((object.ReferenceEquals(this.CATEGORYField, value) != true)) {
                    this.CATEGORYField = value;
                    this.RaisePropertyChanged("CATEGORY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CCY_CD {
            get {
                return this.CCY_CDField;
            }
            set {
                if ((object.ReferenceEquals(this.CCY_CDField, value) != true)) {
                    this.CCY_CDField = value;
                    this.RaisePropertyChanged("CCY_CD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODE {
            get {
                return this.CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.CODEField, value) != true)) {
                    this.CODEField = value;
                    this.RaisePropertyChanged("CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> COUP_DAYS {
            get {
                return this.COUP_DAYSField;
            }
            set {
                if ((this.COUP_DAYSField.Equals(value) != true)) {
                    this.COUP_DAYSField = value;
                    this.RaisePropertyChanged("COUP_DAYS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> COUP_TERM {
            get {
                return this.COUP_TERMField;
            }
            set {
                if ((this.COUP_TERMField.Equals(value) != true)) {
                    this.COUP_TERMField = value;
                    this.RaisePropertyChanged("COUP_TERM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CUSIP {
            get {
                return this.CUSIPField;
            }
            set {
                if ((object.ReferenceEquals(this.CUSIPField, value) != true)) {
                    this.CUSIPField = value;
                    this.RaisePropertyChanged("CUSIP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> INACTIVE {
            get {
                return this.INACTIVEField;
            }
            set {
                if ((this.INACTIVEField.Equals(value) != true)) {
                    this.INACTIVEField = value;
                    this.RaisePropertyChanged("INACTIVE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> INT_RT {
            get {
                return this.INT_RTField;
            }
            set {
                if ((this.INT_RTField.Equals(value) != true)) {
                    this.INT_RTField = value;
                    this.RaisePropertyChanged("INT_RT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> INT_TYPE {
            get {
                return this.INT_TYPEField;
            }
            set {
                if ((this.INT_TYPEField.Equals(value) != true)) {
                    this.INT_TYPEField = value;
                    this.RaisePropertyChanged("INT_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISIN {
            get {
                return this.ISINField;
            }
            set {
                if ((object.ReferenceEquals(this.ISINField, value) != true)) {
                    this.ISINField = value;
                    this.RaisePropertyChanged("ISIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISSUER {
            get {
                return this.ISSUERField;
            }
            set {
                if ((object.ReferenceEquals(this.ISSUERField, value) != true)) {
                    this.ISSUERField = value;
                    this.RaisePropertyChanged("ISSUER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ISSUE_DATE {
            get {
                return this.ISSUE_DATEField;
            }
            set {
                if ((this.ISSUE_DATEField.Equals(value) != true)) {
                    this.ISSUE_DATEField = value;
                    this.RaisePropertyChanged("ISSUE_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IS_DELETED {
            get {
                return this.IS_DELETEDField;
            }
            set {
                if ((this.IS_DELETEDField.Equals(value) != true)) {
                    this.IS_DELETEDField = value;
                    this.RaisePropertyChanged("IS_DELETED");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KSEI_CODE {
            get {
                return this.KSEI_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.KSEI_CODEField, value) != true)) {
                    this.KSEI_CODEField = value;
                    this.RaisePropertyChanged("KSEI_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LAST_COUP {
            get {
                return this.LAST_COUPField;
            }
            set {
                if ((object.ReferenceEquals(this.LAST_COUPField, value) != true)) {
                    this.LAST_COUPField = value;
                    this.RaisePropertyChanged("LAST_COUP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LAST_COUP_DATE {
            get {
                return this.LAST_COUP_DATEField;
            }
            set {
                if ((this.LAST_COUP_DATEField.Equals(value) != true)) {
                    this.LAST_COUP_DATEField = value;
                    this.RaisePropertyChanged("LAST_COUP_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> LIMIT_1 {
            get {
                return this.LIMIT_1Field;
            }
            set {
                if ((this.LIMIT_1Field.Equals(value) != true)) {
                    this.LIMIT_1Field = value;
                    this.RaisePropertyChanged("LIMIT_1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> LIMIT_2 {
            get {
                return this.LIMIT_2Field;
            }
            set {
                if ((this.LIMIT_2Field.Equals(value) != true)) {
                    this.LIMIT_2Field = value;
                    this.RaisePropertyChanged("LIMIT_2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> L_UPD_DATE {
            get {
                return this.L_UPD_DATEField;
            }
            set {
                if ((this.L_UPD_DATEField.Equals(value) != true)) {
                    this.L_UPD_DATEField = value;
                    this.RaisePropertyChanged("L_UPD_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string L_USER_ID {
            get {
                return this.L_USER_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.L_USER_IDField, value) != true)) {
                    this.L_USER_IDField = value;
                    this.RaisePropertyChanged("L_USER_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> MAT_DATE {
            get {
                return this.MAT_DATEField;
            }
            set {
                if ((this.MAT_DATEField.Equals(value) != true)) {
                    this.MAT_DATEField = value;
                    this.RaisePropertyChanged("MAT_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NEXT_COUP {
            get {
                return this.NEXT_COUPField;
            }
            set {
                if ((object.ReferenceEquals(this.NEXT_COUPField, value) != true)) {
                    this.NEXT_COUPField = value;
                    this.RaisePropertyChanged("NEXT_COUP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NEXT_COUP_DATE {
            get {
                return this.NEXT_COUP_DATEField;
            }
            set {
                if ((this.NEXT_COUP_DATEField.Equals(value) != true)) {
                    this.NEXT_COUP_DATEField = value;
                    this.RaisePropertyChanged("NEXT_COUP_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RATING {
            get {
                return this.RATINGField;
            }
            set {
                if ((object.ReferenceEquals(this.RATINGField, value) != true)) {
                    this.RATINGField = value;
                    this.RaisePropertyChanged("RATING");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SECTOR {
            get {
                return this.SECTORField;
            }
            set {
                if ((object.ReferenceEquals(this.SECTORField, value) != true)) {
                    this.SECTORField = value;
                    this.RaisePropertyChanged("SECTOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SEDOLCD {
            get {
                return this.SEDOLCDField;
            }
            set {
                if ((object.ReferenceEquals(this.SEDOLCDField, value) != true)) {
                    this.SEDOLCDField = value;
                    this.RaisePropertyChanged("SEDOLCD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> SYARIAH {
            get {
                return this.SYARIAHField;
            }
            set {
                if ((this.SYARIAHField.Equals(value) != true)) {
                    this.SYARIAHField = value;
                    this.RaisePropertyChanged("SYARIAH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TAX_RT {
            get {
                return this.TAX_RTField;
            }
            set {
                if ((this.TAX_RTField.Equals(value) != true)) {
                    this.TAX_RTField = value;
                    this.RaisePropertyChanged("TAX_RT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TAX_RT_2 {
            get {
                return this.TAX_RT_2Field;
            }
            set {
                if ((this.TAX_RT_2Field.Equals(value) != true)) {
                    this.TAX_RT_2Field = value;
                    this.RaisePropertyChanged("TAX_RT_2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> UNIT_MTD {
            get {
                return this.UNIT_MTDField;
            }
            set {
                if ((this.UNIT_MTDField.Equals(value) != true)) {
                    this.UNIT_MTDField = value;
                    this.RaisePropertyChanged("UNIT_MTD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> YEAR_BS {
            get {
                return this.YEAR_BSField;
            }
            set {
                if ((this.YEAR_BSField.Equals(value) != true)) {
                    this.YEAR_BSField = value;
                    this.RaisePropertyChanged("YEAR_BS");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BondProdResult", Namespace="http://schemas.datacontract.org/2004/07/Manulife.Id.BOAJMI.Bonds.Interface.Dto")]
    [System.SerializableAttribute()]
    public partial class BondProdResult : AbidzarFrame.Web.BOAJMIBondsServiceModel.BondProdBaseModel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BondProdRequest", Namespace="http://schemas.datacontract.org/2004/07/Manulife.Id.BOAJMI.Bonds.Interface.Dto")]
    [System.SerializableAttribute()]
    public partial class BondProdRequest : AbidzarFrame.Web.BOAJMIBondsServiceModel.BondProdBaseModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthenticationTokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthenticationToken {
            get {
                return this.AuthenticationTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthenticationTokenField, value) != true)) {
                    this.AuthenticationTokenField = value;
                    this.RaisePropertyChanged("AuthenticationToken");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BondProdResponse", Namespace="http://schemas.datacontract.org/2004/07/Manulife.Id.BOAJMI.Bonds.Interface.Dto")]
    [System.SerializableAttribute()]
    public partial class BondProdResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AbidzarFrame.Web.BOAJMIBondsServiceModel.BondProdResult BondProdResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AbidzarFrame.Web.BOAJMIBondsServiceModel.BondProdResult[] BondProdResultListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AbidzarFrame.Web.BOAJMIBondsServiceModel.BusinessErrors ErrorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AbidzarFrame.Web.BOAJMIBondsServiceModel.BondProdResult BondProdResult {
            get {
                return this.BondProdResultField;
            }
            set {
                if ((object.ReferenceEquals(this.BondProdResultField, value) != true)) {
                    this.BondProdResultField = value;
                    this.RaisePropertyChanged("BondProdResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AbidzarFrame.Web.BOAJMIBondsServiceModel.BondProdResult[] BondProdResultList {
            get {
                return this.BondProdResultListField;
            }
            set {
                if ((object.ReferenceEquals(this.BondProdResultListField, value) != true)) {
                    this.BondProdResultListField = value;
                    this.RaisePropertyChanged("BondProdResultList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AbidzarFrame.Web.BOAJMIBondsServiceModel.BusinessErrors Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BOAJMIBondsServiceModel.IBondsManager")]
    public interface IBondsManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBondsManager/GetBondMastFindBy", ReplyAction="http://tempuri.org/IBondsManager/GetBondMastFindByResponse")]
        AbidzarFrame.Web.BOAJMIBondsServiceModel.BondMastResponse GetBondMastFindBy(AbidzarFrame.Web.BOAJMIBondsServiceModel.BondMastRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBondsManager/GetBondMastList", ReplyAction="http://tempuri.org/IBondsManager/GetBondMastListResponse")]
        AbidzarFrame.Web.BOAJMIBondsServiceModel.BondMastResponse GetBondMastList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBondsManager/InsertBondMast", ReplyAction="http://tempuri.org/IBondsManager/InsertBondMastResponse")]
        AbidzarFrame.Web.BOAJMIBondsServiceModel.BondMastResponse InsertBondMast(AbidzarFrame.Web.BOAJMIBondsServiceModel.BondMastRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBondsManager/UpdateBondMast", ReplyAction="http://tempuri.org/IBondsManager/UpdateBondMastResponse")]
        AbidzarFrame.Web.BOAJMIBondsServiceModel.BondMastResponse UpdateBondMast(AbidzarFrame.Web.BOAJMIBondsServiceModel.BondMastRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBondsManager/DeleteBondMast", ReplyAction="http://tempuri.org/IBondsManager/DeleteBondMastResponse")]
        AbidzarFrame.Web.BOAJMIBondsServiceModel.BondMastResponse DeleteBondMast(AbidzarFrame.Web.BOAJMIBondsServiceModel.BondMastRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBondsManager/GetBondProdFindBy", ReplyAction="http://tempuri.org/IBondsManager/GetBondProdFindByResponse")]
        AbidzarFrame.Web.BOAJMIBondsServiceModel.BondProdResponse GetBondProdFindBy(AbidzarFrame.Web.BOAJMIBondsServiceModel.BondProdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBondsManager/GetBondProdList", ReplyAction="http://tempuri.org/IBondsManager/GetBondProdListResponse")]
        AbidzarFrame.Web.BOAJMIBondsServiceModel.BondProdResponse GetBondProdList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBondsManager/InsertBondProd", ReplyAction="http://tempuri.org/IBondsManager/InsertBondProdResponse")]
        AbidzarFrame.Web.BOAJMIBondsServiceModel.BondProdResponse InsertBondProd(AbidzarFrame.Web.BOAJMIBondsServiceModel.BondProdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBondsManager/UpdateBondProd", ReplyAction="http://tempuri.org/IBondsManager/UpdateBondProdResponse")]
        AbidzarFrame.Web.BOAJMIBondsServiceModel.BondProdResponse UpdateBondProd(AbidzarFrame.Web.BOAJMIBondsServiceModel.BondProdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBondsManager/DeleteBondProd", ReplyAction="http://tempuri.org/IBondsManager/DeleteBondProdResponse")]
        AbidzarFrame.Web.BOAJMIBondsServiceModel.BondProdResponse DeleteBondProd(AbidzarFrame.Web.BOAJMIBondsServiceModel.BondProdRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBondsManagerChannel : AbidzarFrame.Web.BOAJMIBondsServiceModel.IBondsManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BondsManagerClient : System.ServiceModel.ClientBase<AbidzarFrame.Web.BOAJMIBondsServiceModel.IBondsManager>, AbidzarFrame.Web.BOAJMIBondsServiceModel.IBondsManager {
        
        public BondsManagerClient() {
        }
        
        public BondsManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BondsManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BondsManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BondsManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AbidzarFrame.Web.BOAJMIBondsServiceModel.BondMastResponse GetBondMastFindBy(AbidzarFrame.Web.BOAJMIBondsServiceModel.BondMastRequest request) {
            return base.Channel.GetBondMastFindBy(request);
        }
        
        public AbidzarFrame.Web.BOAJMIBondsServiceModel.BondMastResponse GetBondMastList() {
            return base.Channel.GetBondMastList();
        }
        
        public AbidzarFrame.Web.BOAJMIBondsServiceModel.BondMastResponse InsertBondMast(AbidzarFrame.Web.BOAJMIBondsServiceModel.BondMastRequest request) {
            return base.Channel.InsertBondMast(request);
        }
        
        public AbidzarFrame.Web.BOAJMIBondsServiceModel.BondMastResponse UpdateBondMast(AbidzarFrame.Web.BOAJMIBondsServiceModel.BondMastRequest request) {
            return base.Channel.UpdateBondMast(request);
        }
        
        public AbidzarFrame.Web.BOAJMIBondsServiceModel.BondMastResponse DeleteBondMast(AbidzarFrame.Web.BOAJMIBondsServiceModel.BondMastRequest request) {
            return base.Channel.DeleteBondMast(request);
        }
        
        public AbidzarFrame.Web.BOAJMIBondsServiceModel.BondProdResponse GetBondProdFindBy(AbidzarFrame.Web.BOAJMIBondsServiceModel.BondProdRequest request) {
            return base.Channel.GetBondProdFindBy(request);
        }
        
        public AbidzarFrame.Web.BOAJMIBondsServiceModel.BondProdResponse GetBondProdList() {
            return base.Channel.GetBondProdList();
        }
        
        public AbidzarFrame.Web.BOAJMIBondsServiceModel.BondProdResponse InsertBondProd(AbidzarFrame.Web.BOAJMIBondsServiceModel.BondProdRequest request) {
            return base.Channel.InsertBondProd(request);
        }
        
        public AbidzarFrame.Web.BOAJMIBondsServiceModel.BondProdResponse UpdateBondProd(AbidzarFrame.Web.BOAJMIBondsServiceModel.BondProdRequest request) {
            return base.Channel.UpdateBondProd(request);
        }
        
        public AbidzarFrame.Web.BOAJMIBondsServiceModel.BondProdResponse DeleteBondProd(AbidzarFrame.Web.BOAJMIBondsServiceModel.BondProdRequest request) {
            return base.Channel.DeleteBondProd(request);
        }
    }
}
