//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbidzarFrame.Web.BOAJMIEquityServiceModel {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BrokerBaseModel", Namespace="http://schemas.datacontract.org/2004/07/Manulife.Id.BOAJMI.Domain.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AbidzarFrame.Web.BOAJMIEquityServiceModel.BrokerCodeResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AbidzarFrame.Web.BOAJMIEquityServiceModel.BrokerCodeRequest))]
    public partial class BrokerBaseModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADDRESS1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADDRESS2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADDRESS3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> COMMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DEALERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FAXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FRG_FLGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> INC_TAXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IS_DELETEDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LEVYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> L_UPD_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string L_USER_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MAX_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NPWPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SETTLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TAX_COMMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> VAT_COMMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> VAT_LEVYField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADDRESS1 {
            get {
                return this.ADDRESS1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ADDRESS1Field, value) != true)) {
                    this.ADDRESS1Field = value;
                    this.RaisePropertyChanged("ADDRESS1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADDRESS2 {
            get {
                return this.ADDRESS2Field;
            }
            set {
                if ((object.ReferenceEquals(this.ADDRESS2Field, value) != true)) {
                    this.ADDRESS2Field = value;
                    this.RaisePropertyChanged("ADDRESS2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADDRESS3 {
            get {
                return this.ADDRESS3Field;
            }
            set {
                if ((object.ReferenceEquals(this.ADDRESS3Field, value) != true)) {
                    this.ADDRESS3Field = value;
                    this.RaisePropertyChanged("ADDRESS3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODE {
            get {
                return this.CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.CODEField, value) != true)) {
                    this.CODEField = value;
                    this.RaisePropertyChanged("CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> COMM {
            get {
                return this.COMMField;
            }
            set {
                if ((this.COMMField.Equals(value) != true)) {
                    this.COMMField = value;
                    this.RaisePropertyChanged("COMM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DEALER {
            get {
                return this.DEALERField;
            }
            set {
                if ((object.ReferenceEquals(this.DEALERField, value) != true)) {
                    this.DEALERField = value;
                    this.RaisePropertyChanged("DEALER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESC {
            get {
                return this.DESCField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCField, value) != true)) {
                    this.DESCField = value;
                    this.RaisePropertyChanged("DESC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FAX {
            get {
                return this.FAXField;
            }
            set {
                if ((object.ReferenceEquals(this.FAXField, value) != true)) {
                    this.FAXField = value;
                    this.RaisePropertyChanged("FAX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FRG_FLG {
            get {
                return this.FRG_FLGField;
            }
            set {
                if ((this.FRG_FLGField.Equals(value) != true)) {
                    this.FRG_FLGField = value;
                    this.RaisePropertyChanged("FRG_FLG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> INC_TAX {
            get {
                return this.INC_TAXField;
            }
            set {
                if ((this.INC_TAXField.Equals(value) != true)) {
                    this.INC_TAXField = value;
                    this.RaisePropertyChanged("INC_TAX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IS_DELETED {
            get {
                return this.IS_DELETEDField;
            }
            set {
                if ((this.IS_DELETEDField.Equals(value) != true)) {
                    this.IS_DELETEDField = value;
                    this.RaisePropertyChanged("IS_DELETED");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> LEVY {
            get {
                return this.LEVYField;
            }
            set {
                if ((this.LEVYField.Equals(value) != true)) {
                    this.LEVYField = value;
                    this.RaisePropertyChanged("LEVY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> L_UPD_DATE {
            get {
                return this.L_UPD_DATEField;
            }
            set {
                if ((this.L_UPD_DATEField.Equals(value) != true)) {
                    this.L_UPD_DATEField = value;
                    this.RaisePropertyChanged("L_UPD_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string L_USER_ID {
            get {
                return this.L_USER_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.L_USER_IDField, value) != true)) {
                    this.L_USER_IDField = value;
                    this.RaisePropertyChanged("L_USER_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MAX_CODE {
            get {
                return this.MAX_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.MAX_CODEField, value) != true)) {
                    this.MAX_CODEField = value;
                    this.RaisePropertyChanged("MAX_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NPWP {
            get {
                return this.NPWPField;
            }
            set {
                if ((object.ReferenceEquals(this.NPWPField, value) != true)) {
                    this.NPWPField = value;
                    this.RaisePropertyChanged("NPWP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SETTLE {
            get {
                return this.SETTLEField;
            }
            set {
                if ((object.ReferenceEquals(this.SETTLEField, value) != true)) {
                    this.SETTLEField = value;
                    this.RaisePropertyChanged("SETTLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TAX_COMM {
            get {
                return this.TAX_COMMField;
            }
            set {
                if ((this.TAX_COMMField.Equals(value) != true)) {
                    this.TAX_COMMField = value;
                    this.RaisePropertyChanged("TAX_COMM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> VAT_COMM {
            get {
                return this.VAT_COMMField;
            }
            set {
                if ((this.VAT_COMMField.Equals(value) != true)) {
                    this.VAT_COMMField = value;
                    this.RaisePropertyChanged("VAT_COMM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> VAT_LEVY {
            get {
                return this.VAT_LEVYField;
            }
            set {
                if ((this.VAT_LEVYField.Equals(value) != true)) {
                    this.VAT_LEVYField = value;
                    this.RaisePropertyChanged("VAT_LEVY");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BrokerCodeResult", Namespace="http://schemas.datacontract.org/2004/07/Manulife.Id.BOAJMI.Equity.Interface.Dto")]
    [System.SerializableAttribute()]
    public partial class BrokerCodeResult : AbidzarFrame.Web.BOAJMIEquityServiceModel.BrokerBaseModel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BrokerCodeRequest", Namespace="http://schemas.datacontract.org/2004/07/Manulife.Id.BOAJMI.Equity.Interface.Dto")]
    [System.SerializableAttribute()]
    public partial class BrokerCodeRequest : AbidzarFrame.Web.BOAJMIEquityServiceModel.BrokerBaseModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthenticationTokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthenticationToken {
            get {
                return this.AuthenticationTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthenticationTokenField, value) != true)) {
                    this.AuthenticationTokenField = value;
                    this.RaisePropertyChanged("AuthenticationToken");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BrokerCodeResponse", Namespace="http://schemas.datacontract.org/2004/07/Manulife.Id.BOAJMI.Equity.Interface.Dto")]
    [System.SerializableAttribute()]
    public partial class BrokerCodeResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AbidzarFrame.Web.BOAJMIEquityServiceModel.BrokerCodeResult BrokerCodeResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AbidzarFrame.Web.BOAJMIEquityServiceModel.BrokerCodeResult[] BrokerCodeResultListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AbidzarFrame.Web.BOAJMIEquityServiceModel.BusinessErrors ErrorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AbidzarFrame.Web.BOAJMIEquityServiceModel.BrokerCodeResult BrokerCodeResult {
            get {
                return this.BrokerCodeResultField;
            }
            set {
                if ((object.ReferenceEquals(this.BrokerCodeResultField, value) != true)) {
                    this.BrokerCodeResultField = value;
                    this.RaisePropertyChanged("BrokerCodeResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AbidzarFrame.Web.BOAJMIEquityServiceModel.BrokerCodeResult[] BrokerCodeResultList {
            get {
                return this.BrokerCodeResultListField;
            }
            set {
                if ((object.ReferenceEquals(this.BrokerCodeResultListField, value) != true)) {
                    this.BrokerCodeResultListField = value;
                    this.RaisePropertyChanged("BrokerCodeResultList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AbidzarFrame.Web.BOAJMIEquityServiceModel.BusinessErrors Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessErrors", Namespace="http://schemas.datacontract.org/2004/07/Manulife.Core.Model.Business")]
    [System.SerializableAttribute()]
    public partial class BusinessErrors : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AbidzarFrame.Web.BOAJMIEquityServiceModel.BusinessErrorVo[] ErrorListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AbidzarFrame.Web.BOAJMIEquityServiceModel.BusinessErrorVo[] ErrorList {
            get {
                return this.ErrorListField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorListField, value) != true)) {
                    this.ErrorListField = value;
                    this.RaisePropertyChanged("ErrorList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessErrorVo", Namespace="http://schemas.datacontract.org/2004/07/Manulife.Core.Model.Business")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AbidzarFrame.Web.BOAJMIEquityServiceModel.BusinessWarningVo))]
    public partial class BusinessErrorVo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> ErrorMessagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorField {
            get {
                return this.ErrorFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorFieldField, value) != true)) {
                    this.ErrorFieldField = value;
                    this.RaisePropertyChanged("ErrorField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> ErrorMessages {
            get {
                return this.ErrorMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessagesField, value) != true)) {
                    this.ErrorMessagesField = value;
                    this.RaisePropertyChanged("ErrorMessages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessWarningVo", Namespace="http://schemas.datacontract.org/2004/07/Manulife.Core.Model.Business")]
    [System.SerializableAttribute()]
    public partial class BusinessWarningVo : AbidzarFrame.Web.BOAJMIEquityServiceModel.BusinessErrorVo {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EquityHBaseModel", Namespace="http://schemas.datacontract.org/2004/07/Manulife.Id.BOAJMI.Domain.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityHeaderResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityHeaderRequest))]
    public partial class EquityHBaseModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ACC_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ACC_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APPROVEDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BANK_ACCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COMMENTARYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DEAL_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ENT_DTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EXECUTEDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FUND_DESCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GROUP_CDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IS_DELETEDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> L_UPD_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string L_USER_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ORDER_TPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SECUR_TPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SETTLEMENTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SETTLE_DTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SET_AMOUNTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TRAN_DTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TRAN_TYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USER_ID_AField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UniqueIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ACC_NAME {
            get {
                return this.ACC_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.ACC_NAMEField, value) != true)) {
                    this.ACC_NAMEField = value;
                    this.RaisePropertyChanged("ACC_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ACC_NO {
            get {
                return this.ACC_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.ACC_NOField, value) != true)) {
                    this.ACC_NOField = value;
                    this.RaisePropertyChanged("ACC_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APPROVED {
            get {
                return this.APPROVEDField;
            }
            set {
                if ((object.ReferenceEquals(this.APPROVEDField, value) != true)) {
                    this.APPROVEDField = value;
                    this.RaisePropertyChanged("APPROVED");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BANK_ACC {
            get {
                return this.BANK_ACCField;
            }
            set {
                if ((object.ReferenceEquals(this.BANK_ACCField, value) != true)) {
                    this.BANK_ACCField = value;
                    this.RaisePropertyChanged("BANK_ACC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COMMENTARY {
            get {
                return this.COMMENTARYField;
            }
            set {
                if ((object.ReferenceEquals(this.COMMENTARYField, value) != true)) {
                    this.COMMENTARYField = value;
                    this.RaisePropertyChanged("COMMENTARY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DEAL_NO {
            get {
                return this.DEAL_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.DEAL_NOField, value) != true)) {
                    this.DEAL_NOField = value;
                    this.RaisePropertyChanged("DEAL_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ENT_DT {
            get {
                return this.ENT_DTField;
            }
            set {
                if ((object.ReferenceEquals(this.ENT_DTField, value) != true)) {
                    this.ENT_DTField = value;
                    this.RaisePropertyChanged("ENT_DT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EXECUTED {
            get {
                return this.EXECUTEDField;
            }
            set {
                if ((object.ReferenceEquals(this.EXECUTEDField, value) != true)) {
                    this.EXECUTEDField = value;
                    this.RaisePropertyChanged("EXECUTED");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FUND_DESC {
            get {
                return this.FUND_DESCField;
            }
            set {
                if ((object.ReferenceEquals(this.FUND_DESCField, value) != true)) {
                    this.FUND_DESCField = value;
                    this.RaisePropertyChanged("FUND_DESC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GROUP_CD {
            get {
                return this.GROUP_CDField;
            }
            set {
                if ((object.ReferenceEquals(this.GROUP_CDField, value) != true)) {
                    this.GROUP_CDField = value;
                    this.RaisePropertyChanged("GROUP_CD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IS_DELETED {
            get {
                return this.IS_DELETEDField;
            }
            set {
                if ((this.IS_DELETEDField.Equals(value) != true)) {
                    this.IS_DELETEDField = value;
                    this.RaisePropertyChanged("IS_DELETED");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> L_UPD_DATE {
            get {
                return this.L_UPD_DATEField;
            }
            set {
                if ((this.L_UPD_DATEField.Equals(value) != true)) {
                    this.L_UPD_DATEField = value;
                    this.RaisePropertyChanged("L_UPD_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string L_USER_ID {
            get {
                return this.L_USER_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.L_USER_IDField, value) != true)) {
                    this.L_USER_IDField = value;
                    this.RaisePropertyChanged("L_USER_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ORDER_TP {
            get {
                return this.ORDER_TPField;
            }
            set {
                if ((this.ORDER_TPField.Equals(value) != true)) {
                    this.ORDER_TPField = value;
                    this.RaisePropertyChanged("ORDER_TP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SECUR_TP {
            get {
                return this.SECUR_TPField;
            }
            set {
                if ((this.SECUR_TPField.Equals(value) != true)) {
                    this.SECUR_TPField = value;
                    this.RaisePropertyChanged("SECUR_TP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SETTLEMENT {
            get {
                return this.SETTLEMENTField;
            }
            set {
                if ((object.ReferenceEquals(this.SETTLEMENTField, value) != true)) {
                    this.SETTLEMENTField = value;
                    this.RaisePropertyChanged("SETTLEMENT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SETTLE_DT {
            get {
                return this.SETTLE_DTField;
            }
            set {
                if ((this.SETTLE_DTField.Equals(value) != true)) {
                    this.SETTLE_DTField = value;
                    this.RaisePropertyChanged("SETTLE_DT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SET_AMOUNT {
            get {
                return this.SET_AMOUNTField;
            }
            set {
                if ((this.SET_AMOUNTField.Equals(value) != true)) {
                    this.SET_AMOUNTField = value;
                    this.RaisePropertyChanged("SET_AMOUNT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TRAN_DT {
            get {
                return this.TRAN_DTField;
            }
            set {
                if ((this.TRAN_DTField.Equals(value) != true)) {
                    this.TRAN_DTField = value;
                    this.RaisePropertyChanged("TRAN_DT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TRAN_TYPE {
            get {
                return this.TRAN_TYPEField;
            }
            set {
                if ((this.TRAN_TYPEField.Equals(value) != true)) {
                    this.TRAN_TYPEField = value;
                    this.RaisePropertyChanged("TRAN_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USER_ID_A {
            get {
                return this.USER_ID_AField;
            }
            set {
                if ((object.ReferenceEquals(this.USER_ID_AField, value) != true)) {
                    this.USER_ID_AField = value;
                    this.RaisePropertyChanged("USER_ID_A");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UniqueId {
            get {
                return this.UniqueIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UniqueIdField, value) != true)) {
                    this.UniqueIdField = value;
                    this.RaisePropertyChanged("UniqueId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EquityHeaderResult", Namespace="http://schemas.datacontract.org/2004/07/Manulife.Id.BOAJMI.Equity.Interface.Dto")]
    [System.SerializableAttribute()]
    public partial class EquityHeaderResult : AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityHBaseModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityDetailResult[] EquityDetailResultListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityDetailResult[] EquityDetailResultList {
            get {
                return this.EquityDetailResultListField;
            }
            set {
                if ((object.ReferenceEquals(this.EquityDetailResultListField, value) != true)) {
                    this.EquityDetailResultListField = value;
                    this.RaisePropertyChanged("EquityDetailResultList");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EquityHeaderRequest", Namespace="http://schemas.datacontract.org/2004/07/Manulife.Id.BOAJMI.Equity.Interface.Dto")]
    [System.SerializableAttribute()]
    public partial class EquityHeaderRequest : AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityHBaseModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthenticationTokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthenticationToken {
            get {
                return this.AuthenticationTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthenticationTokenField, value) != true)) {
                    this.AuthenticationTokenField = value;
                    this.RaisePropertyChanged("AuthenticationToken");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EquityDetailResult", Namespace="http://schemas.datacontract.org/2004/07/Manulife.Id.BOAJMI.Equity.Interface.Dto")]
    [System.SerializableAttribute()]
    public partial class EquityDetailResult : AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityDBaseModel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EquityDBaseModel", Namespace="http://schemas.datacontract.org/2004/07/Manulife.Id.BOAJMI.Domain.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityDetailRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityDetailResult))]
    public partial class EquityDBaseModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BROKER_CDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> COMMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DEAL_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EQUITY_D_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> INC_TAXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IS_DELETEDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LEVYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> L_UPD_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string L_USER_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ORDER_TPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PRICE_EXECField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PRICE_ORDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> QTY_EXECField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> QTY_ORDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SECUR_CDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SPEC_INSTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TAX_COMMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TOTALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UniqueIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> VAT_COMMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> VAT_LEVYField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BROKER_CD {
            get {
                return this.BROKER_CDField;
            }
            set {
                if ((object.ReferenceEquals(this.BROKER_CDField, value) != true)) {
                    this.BROKER_CDField = value;
                    this.RaisePropertyChanged("BROKER_CD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> COMM {
            get {
                return this.COMMField;
            }
            set {
                if ((this.COMMField.Equals(value) != true)) {
                    this.COMMField = value;
                    this.RaisePropertyChanged("COMM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DEAL_NO {
            get {
                return this.DEAL_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.DEAL_NOField, value) != true)) {
                    this.DEAL_NOField = value;
                    this.RaisePropertyChanged("DEAL_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EQUITY_D_ID {
            get {
                return this.EQUITY_D_IDField;
            }
            set {
                if ((this.EQUITY_D_IDField.Equals(value) != true)) {
                    this.EQUITY_D_IDField = value;
                    this.RaisePropertyChanged("EQUITY_D_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> INC_TAX {
            get {
                return this.INC_TAXField;
            }
            set {
                if ((this.INC_TAXField.Equals(value) != true)) {
                    this.INC_TAXField = value;
                    this.RaisePropertyChanged("INC_TAX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IS_DELETED {
            get {
                return this.IS_DELETEDField;
            }
            set {
                if ((this.IS_DELETEDField.Equals(value) != true)) {
                    this.IS_DELETEDField = value;
                    this.RaisePropertyChanged("IS_DELETED");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> LEVY {
            get {
                return this.LEVYField;
            }
            set {
                if ((this.LEVYField.Equals(value) != true)) {
                    this.LEVYField = value;
                    this.RaisePropertyChanged("LEVY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> L_UPD_DATE {
            get {
                return this.L_UPD_DATEField;
            }
            set {
                if ((this.L_UPD_DATEField.Equals(value) != true)) {
                    this.L_UPD_DATEField = value;
                    this.RaisePropertyChanged("L_UPD_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string L_USER_ID {
            get {
                return this.L_USER_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.L_USER_IDField, value) != true)) {
                    this.L_USER_IDField = value;
                    this.RaisePropertyChanged("L_USER_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ORDER_TP {
            get {
                return this.ORDER_TPField;
            }
            set {
                if ((this.ORDER_TPField.Equals(value) != true)) {
                    this.ORDER_TPField = value;
                    this.RaisePropertyChanged("ORDER_TP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PRICE_EXEC {
            get {
                return this.PRICE_EXECField;
            }
            set {
                if ((this.PRICE_EXECField.Equals(value) != true)) {
                    this.PRICE_EXECField = value;
                    this.RaisePropertyChanged("PRICE_EXEC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PRICE_ORD {
            get {
                return this.PRICE_ORDField;
            }
            set {
                if ((this.PRICE_ORDField.Equals(value) != true)) {
                    this.PRICE_ORDField = value;
                    this.RaisePropertyChanged("PRICE_ORD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> QTY_EXEC {
            get {
                return this.QTY_EXECField;
            }
            set {
                if ((this.QTY_EXECField.Equals(value) != true)) {
                    this.QTY_EXECField = value;
                    this.RaisePropertyChanged("QTY_EXEC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> QTY_ORD {
            get {
                return this.QTY_ORDField;
            }
            set {
                if ((this.QTY_ORDField.Equals(value) != true)) {
                    this.QTY_ORDField = value;
                    this.RaisePropertyChanged("QTY_ORD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SECUR_CD {
            get {
                return this.SECUR_CDField;
            }
            set {
                if ((object.ReferenceEquals(this.SECUR_CDField, value) != true)) {
                    this.SECUR_CDField = value;
                    this.RaisePropertyChanged("SECUR_CD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SPEC_INST {
            get {
                return this.SPEC_INSTField;
            }
            set {
                if ((this.SPEC_INSTField.Equals(value) != true)) {
                    this.SPEC_INSTField = value;
                    this.RaisePropertyChanged("SPEC_INST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TAX_COMM {
            get {
                return this.TAX_COMMField;
            }
            set {
                if ((this.TAX_COMMField.Equals(value) != true)) {
                    this.TAX_COMMField = value;
                    this.RaisePropertyChanged("TAX_COMM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TOTAL {
            get {
                return this.TOTALField;
            }
            set {
                if ((this.TOTALField.Equals(value) != true)) {
                    this.TOTALField = value;
                    this.RaisePropertyChanged("TOTAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UniqueId {
            get {
                return this.UniqueIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UniqueIdField, value) != true)) {
                    this.UniqueIdField = value;
                    this.RaisePropertyChanged("UniqueId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> VAT_COMM {
            get {
                return this.VAT_COMMField;
            }
            set {
                if ((this.VAT_COMMField.Equals(value) != true)) {
                    this.VAT_COMMField = value;
                    this.RaisePropertyChanged("VAT_COMM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> VAT_LEVY {
            get {
                return this.VAT_LEVYField;
            }
            set {
                if ((this.VAT_LEVYField.Equals(value) != true)) {
                    this.VAT_LEVYField = value;
                    this.RaisePropertyChanged("VAT_LEVY");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EquityDetailRequest", Namespace="http://schemas.datacontract.org/2004/07/Manulife.Id.BOAJMI.Equity.Interface.Dto")]
    [System.SerializableAttribute()]
    public partial class EquityDetailRequest : AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityDBaseModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthenticationTokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthenticationToken {
            get {
                return this.AuthenticationTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthenticationTokenField, value) != true)) {
                    this.AuthenticationTokenField = value;
                    this.RaisePropertyChanged("AuthenticationToken");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EquityHeaderResponse", Namespace="http://schemas.datacontract.org/2004/07/Manulife.Id.BOAJMI.Equity.Interface.Dto")]
    [System.SerializableAttribute()]
    public partial class EquityHeaderResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityHeaderResult EquityHeaderResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityHeaderResult[] EquityHeaderResultListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AbidzarFrame.Web.BOAJMIEquityServiceModel.BusinessErrors ErrorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityHeaderResult EquityHeaderResult {
            get {
                return this.EquityHeaderResultField;
            }
            set {
                if ((object.ReferenceEquals(this.EquityHeaderResultField, value) != true)) {
                    this.EquityHeaderResultField = value;
                    this.RaisePropertyChanged("EquityHeaderResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityHeaderResult[] EquityHeaderResultList {
            get {
                return this.EquityHeaderResultListField;
            }
            set {
                if ((object.ReferenceEquals(this.EquityHeaderResultListField, value) != true)) {
                    this.EquityHeaderResultListField = value;
                    this.RaisePropertyChanged("EquityHeaderResultList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AbidzarFrame.Web.BOAJMIEquityServiceModel.BusinessErrors Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EquityDetailResponse", Namespace="http://schemas.datacontract.org/2004/07/Manulife.Id.BOAJMI.Equity.Interface.Dto")]
    [System.SerializableAttribute()]
    public partial class EquityDetailResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityDetailResult EquityDetailResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityDetailResult[] EquityDetailResultListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AbidzarFrame.Web.BOAJMIEquityServiceModel.BusinessErrors ErrorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityDetailResult EquityDetailResult {
            get {
                return this.EquityDetailResultField;
            }
            set {
                if ((object.ReferenceEquals(this.EquityDetailResultField, value) != true)) {
                    this.EquityDetailResultField = value;
                    this.RaisePropertyChanged("EquityDetailResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityDetailResult[] EquityDetailResultList {
            get {
                return this.EquityDetailResultListField;
            }
            set {
                if ((object.ReferenceEquals(this.EquityDetailResultListField, value) != true)) {
                    this.EquityDetailResultListField = value;
                    this.RaisePropertyChanged("EquityDetailResultList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AbidzarFrame.Web.BOAJMIEquityServiceModel.BusinessErrors Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BOAJMIEquityServiceModel.IEquityManager")]
    public interface IEquityManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquityManager/GetBrokerCodeFindBy", ReplyAction="http://tempuri.org/IEquityManager/GetBrokerCodeFindByResponse")]
        AbidzarFrame.Web.BOAJMIEquityServiceModel.BrokerCodeResponse GetBrokerCodeFindBy(AbidzarFrame.Web.BOAJMIEquityServiceModel.BrokerCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquityManager/GetBrokerCodeList", ReplyAction="http://tempuri.org/IEquityManager/GetBrokerCodeListResponse")]
        AbidzarFrame.Web.BOAJMIEquityServiceModel.BrokerCodeResponse GetBrokerCodeList(AbidzarFrame.Web.BOAJMIEquityServiceModel.BrokerCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquityManager/InsertBrokerCode", ReplyAction="http://tempuri.org/IEquityManager/InsertBrokerCodeResponse")]
        AbidzarFrame.Web.BOAJMIEquityServiceModel.BrokerCodeResponse InsertBrokerCode(AbidzarFrame.Web.BOAJMIEquityServiceModel.BrokerCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquityManager/UpdateBrokerCode", ReplyAction="http://tempuri.org/IEquityManager/UpdateBrokerCodeResponse")]
        AbidzarFrame.Web.BOAJMIEquityServiceModel.BrokerCodeResponse UpdateBrokerCode(AbidzarFrame.Web.BOAJMIEquityServiceModel.BrokerCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquityManager/DeleteBrokerCode", ReplyAction="http://tempuri.org/IEquityManager/DeleteBrokerCodeResponse")]
        AbidzarFrame.Web.BOAJMIEquityServiceModel.BrokerCodeResponse DeleteBrokerCode(AbidzarFrame.Web.BOAJMIEquityServiceModel.BrokerCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquityManager/GetEquityHeadFindBy", ReplyAction="http://tempuri.org/IEquityManager/GetEquityHeadFindByResponse")]
        AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityHeaderResponse GetEquityHeadFindBy(AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityHeaderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquityManager/GetEquityHeaderList", ReplyAction="http://tempuri.org/IEquityManager/GetEquityHeaderListResponse")]
        AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityHeaderResponse GetEquityHeaderList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquityManager/InsertEquityHeader", ReplyAction="http://tempuri.org/IEquityManager/InsertEquityHeaderResponse")]
        AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityHeaderResponse InsertEquityHeader(AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityHeaderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquityManager/UpdateEquityHeader", ReplyAction="http://tempuri.org/IEquityManager/UpdateEquityHeaderResponse")]
        AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityHeaderResponse UpdateEquityHeader(AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityHeaderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquityManager/DeleteEquityHeader", ReplyAction="http://tempuri.org/IEquityManager/DeleteEquityHeaderResponse")]
        AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityHeaderResponse DeleteEquityHeader(AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityHeaderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquityManager/GetEquityDetailFindBy", ReplyAction="http://tempuri.org/IEquityManager/GetEquityDetailFindByResponse")]
        AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityDetailResponse GetEquityDetailFindBy(AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquityManager/GetEquityDetailList", ReplyAction="http://tempuri.org/IEquityManager/GetEquityDetailListResponse")]
        AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityDetailResponse GetEquityDetailList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquityManager/InsertEquityDetail", ReplyAction="http://tempuri.org/IEquityManager/InsertEquityDetailResponse")]
        AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityDetailResponse InsertEquityDetail(AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquityManager/UpdateEquityDetail", ReplyAction="http://tempuri.org/IEquityManager/UpdateEquityDetailResponse")]
        AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityDetailResponse UpdateEquityDetail(AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquityManager/DeleteEquityDetail", ReplyAction="http://tempuri.org/IEquityManager/DeleteEquityDetailResponse")]
        AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityDetailResponse DeleteEquityDetail(AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityDetailRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEquityManagerChannel : AbidzarFrame.Web.BOAJMIEquityServiceModel.IEquityManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EquityManagerClient : System.ServiceModel.ClientBase<AbidzarFrame.Web.BOAJMIEquityServiceModel.IEquityManager>, AbidzarFrame.Web.BOAJMIEquityServiceModel.IEquityManager {
        
        public EquityManagerClient() {
        }
        
        public EquityManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EquityManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EquityManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EquityManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AbidzarFrame.Web.BOAJMIEquityServiceModel.BrokerCodeResponse GetBrokerCodeFindBy(AbidzarFrame.Web.BOAJMIEquityServiceModel.BrokerCodeRequest request) {
            return base.Channel.GetBrokerCodeFindBy(request);
        }
        
        public AbidzarFrame.Web.BOAJMIEquityServiceModel.BrokerCodeResponse GetBrokerCodeList(AbidzarFrame.Web.BOAJMIEquityServiceModel.BrokerCodeRequest request) {
            return base.Channel.GetBrokerCodeList(request);
        }
        
        public AbidzarFrame.Web.BOAJMIEquityServiceModel.BrokerCodeResponse InsertBrokerCode(AbidzarFrame.Web.BOAJMIEquityServiceModel.BrokerCodeRequest request) {
            return base.Channel.InsertBrokerCode(request);
        }
        
        public AbidzarFrame.Web.BOAJMIEquityServiceModel.BrokerCodeResponse UpdateBrokerCode(AbidzarFrame.Web.BOAJMIEquityServiceModel.BrokerCodeRequest request) {
            return base.Channel.UpdateBrokerCode(request);
        }
        
        public AbidzarFrame.Web.BOAJMIEquityServiceModel.BrokerCodeResponse DeleteBrokerCode(AbidzarFrame.Web.BOAJMIEquityServiceModel.BrokerCodeRequest request) {
            return base.Channel.DeleteBrokerCode(request);
        }
        
        public AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityHeaderResponse GetEquityHeadFindBy(AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityHeaderRequest request) {
            return base.Channel.GetEquityHeadFindBy(request);
        }
        
        public AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityHeaderResponse GetEquityHeaderList() {
            return base.Channel.GetEquityHeaderList();
        }
        
        public AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityHeaderResponse InsertEquityHeader(AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityHeaderRequest request) {
            return base.Channel.InsertEquityHeader(request);
        }
        
        public AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityHeaderResponse UpdateEquityHeader(AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityHeaderRequest request) {
            return base.Channel.UpdateEquityHeader(request);
        }
        
        public AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityHeaderResponse DeleteEquityHeader(AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityHeaderRequest request) {
            return base.Channel.DeleteEquityHeader(request);
        }
        
        public AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityDetailResponse GetEquityDetailFindBy(AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityDetailRequest request) {
            return base.Channel.GetEquityDetailFindBy(request);
        }
        
        public AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityDetailResponse GetEquityDetailList() {
            return base.Channel.GetEquityDetailList();
        }
        
        public AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityDetailResponse InsertEquityDetail(AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityDetailRequest request) {
            return base.Channel.InsertEquityDetail(request);
        }
        
        public AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityDetailResponse UpdateEquityDetail(AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityDetailRequest request) {
            return base.Channel.UpdateEquityDetail(request);
        }
        
        public AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityDetailResponse DeleteEquityDetail(AbidzarFrame.Web.BOAJMIEquityServiceModel.EquityDetailRequest request) {
            return base.Channel.DeleteEquityDetail(request);
        }
    }
}
